<?xml version="1.0" encoding="utf-8"?><Database Name="CXKdb" Class="CXKdbmlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\CXKdb.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CXKdbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Userdb" Member="Userdb">
    <Type Name="Userdb">
      <Column Name="userid" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="sex" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Column Name="shouhuodizhi" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="phonenum" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>